# Generated by Django 4.2.27 on 2025-12-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviterequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
