# Generated by Django 4.2.27 on 2025-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0002_alter_inviterequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
