# Generated by Django 4.2.27 on 2025-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0003_pilotprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=8),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
