# Generated by Django 4.2.27 on 2025-12-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0005_pilotprofile_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inviterequest',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
