# Generated by Django 4.2.27 on 2025-12-29 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0007_userfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
