# Generated by Django 4.2.27 on 2026-01-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0008_userfilter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='inviterequest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
