# Generated by Django 4.2.27 on 2026-01-05 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0009_alter_invitation_phone_alter_inviterequest_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.CharField(editable=False, help_text='Auto-generated 6-digit unique campaign code', max_length=6, unique=True)),
                ('valid_from', models.DateField(help_text='Campaign start date (inclusive)')),
                ('valid_to', models.DateField(help_text='Campaign end date (inclusive)')),
                ('comment', models.TextField(help_text='Campaign description/comment (displayed to users)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
