# Generated by Django 4.2.27 on 2026-01-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0010_campaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='InviteRequest',
        ),
    ]
