# Generated by Django 4.2.27 on 2026-01-05 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_access', '0011_delete_invitation_delete_inviterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotprofile',
            name='invited_at',
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='pilot_access.campaign', to_field='campaign_code'),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
