# Generated by Django 4.2.30 on 2026-04-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('htsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(blank=True, default='', max_length=255)),
                ('priority_behaviour', models.CharField(blank=True, default='', max_length=255)),
                ('past_barriers', models.JSONField(blank=True, default=list)),
                ('current_barriers', models.JSONField(blank=True, default=list)),
                ('confidence_readiness', models.CharField(blank=True, default='', max_length=255)),
                ('enablers', models.JSONField(blank=True, default=list)),
                ('behavioural_tags', models.JSONField(blank=True, default=dict)),
                ('activity_attributes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questionnaire_response',
            },
        ),
    ]
