# Generated by Django 4.2.30 on 2026-04-16 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('htsh', '0002_questionnaire_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'activity_attribute',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceActivityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField(db_index=True, help_text='V3_Service.id — not a FK because the service table is unmanaged')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='htsh.activityattribute')),
            ],
            options={
                'db_table': 'service_activity_attribute',
                'ordering': ['service_id', 'attribute__name'],
                'unique_together': {('service_id', 'attribute')},
            },
        ),
    ]
