name: Deploy App Layer - Dev

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string
        default: latest
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
        default: plan
      environment_suffix:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - poc
          - dev
          - sandbox
        default: poc
      include_app_vars:
        required: false
        type: boolean
        default: true

env:
  PROJECT:           ${{ vars.PROJECT }}
  AWS_REGION:        ${{ vars.AWS_REGION }}
  GH_ENV:            dev
  INCLUDE_APP_VARS:   ${{ inputs.include_app_vars }}

jobs:
  plan-app-dev:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: dev
      environment_suffix: ${{ inputs.environment_suffix }}
      layer: app
      working_directory: infra/terraform/environments/dev/app
      image_tag: ${{ inputs.image_tag }}
      aws_region: ${{ vars.AWS_REGION }}
      aws_account_id: 515424599516
      project: nhse-pps-htsh
      gh_env: dev
      include_app_vars: ${{ inputs.include_app_vars }}

  apply-app-dev:
    if: inputs.action == 'apply'
    needs: plan-app-dev
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: dev
      environment_suffix: ${{ inputs.environment_suffix }}
      layer: app
      working_directory: infra/terraform/environments/dev/app
      aws_region: ${{ vars.AWS_REGION }}
      aws_account_id: 515424599516
      project: nhse-pps-htsh
      gh_env: dev
      include_app_vars: ${{ inputs.include_app_vars }}