name: Deploy Datastore Layer - Dev

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan
      dry_run:
        description: 'Perform a dry run (destroy only)'
        required: false
        type: boolean
        default: true

env:
  PROJECT:           ${{ vars.PROJECT }}
  AWS_REGION:        ${{ vars.AWS_REGION }}
  GH_ENV:            dev

jobs:
  plan-datastore-dev:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: dev
      layer: datastore
      working_directory: infra/terraform/environments/dev/datastore
      aws_region: ${{ vars.AWS_REGION }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      project: nhse-pps-htsh
      gh_env: dev

  apply-datastore-dev:
    if: inputs.action == 'apply'
    needs: plan-datastore-dev
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: dev
      layer: datastore
      working_directory: infra/terraform/environments/dev/datastore
      aws_region: ${{ vars.AWS_REGION }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      project: nhse-pps-htsh
      gh_env: dev
  
  destroy-datastore-dev:
    if: inputs.action == 'destroy'
    needs: plan-datastore-dev
    uses: ./.github/workflows/terraform-destroy.yml
    with:
      environment: dev
      layer: datastore
      working_directory: infra/terraform/environments/dev/datastore
      aws_region: ${{ vars.AWS_REGION }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      project: nhse-pps-htsh
      gh_env: dev
      dry_run: ${{ inputs.dry_run }}